color.badge.default="secondary"

color.badge.pandas="danger"

color.badge.hive="info"

color.badge.bash="light"

color.badge.link="primary"

color.badge.memo="secondary"

color.badge.error="secondary"

color.badge.hadoop-streaming="secondary"